apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ruby-todoapp
spec:
  template:
    metadata:
      labels:
        app: ruby-todoapp
    spec:
      containers:
      - name: ruby-todoapp
        image: ghcr.io/mattn/ruby-todoapp
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: todoapp
              key: database-url
        ports:
        - containerPort: 8989
          protocol: TCP
